# Azure pipeline definition for the packaging of the solution (continuous delivery)
# See: https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pr: none

variables:
# library variable groups
- group: 'build-tools'
# environment variables
- name: DOTNET_CLI_TELEMETRY_OPTOUT
  value: 1
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: 1
# common task variables
- name: 'BuildConfiguration'
  value: 'Release'
- name: 'SolutionFile'
  value: 'dotnet/KeepTrack.sln'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.1.100'
  inputs:
    packageType: 'sdk'
    version: '3.1.100'
- task: DotNetCoreCLI@2
  displayName: 'Publish the ASP.NET API'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'dotnet/src/**/*Api.csproj'
    arguments: '-c $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)/aspnetapi'
    modifyOutputPath: false
- task: DotNetCoreCLI@2
  displayName: 'Publish the ASP.NET Angular App'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'dotnet/src/**/AngularWebApp.csproj'
    arguments: '-c $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)/aspnetangular'
    modifyOutputPath: false
- task: PublishBuildArtifacts@1
  displayName: 'Save the artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
