# Azure pipeline definition for the packaging of the solution (continuous delivery)
# See: https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pr: none

variables:
# library variable groups
- group: 'build-tools'
# environment variables
- name: DOTNET_CLI_TELEMETRY_OPTOUT
  value: 1
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: 1
# common task variables
- name: 'BuildConfiguration'
  value: 'Release'
- name: 'SolutionFile'
  value: 'dotnet/KeepTrack.sln'
# build environment
- name: 'angular.build.configuration'
  value: 'production'

pool:
  vmImage: 'ubuntu-latest'

steps:
# ASP.NET Core web application
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.1.100'
  inputs:
    packageType: 'sdk'
    version: '3.1.100'
- task: DotNetCoreCLI@2
  displayName: 'Publish the ASP.NET API'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'dotnet/src/**/*Api.csproj'
    arguments: '-c $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)/aspnetapi'
    modifyOutputPath: false
# Angular web application
- task: Npm@1
  displayName: 'Install Angular CLI'
  inputs:
    command: 'custom'
    customCommand: 'install -g @angular/cli@8.3.25'
- task: Npm@1
  displayName: 'Install NPM packages'
  inputs:
    command: 'install'
    workingDir: 'angular-bootstrap'
- task: CmdLine@2
  displayName: 'Build Angular application'
  inputs:
    script: |
      ng build --configuration="$(angular.build.configuration)" --outputPath="$(Build.ArtifactStagingDirectory)/angularbootstrap"
    workingDirectory: 'angular-bootstrap'
- task: PublishBuildArtifacts@1
  displayName: 'Save artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
