# Azure pipeline definition for the packaging of the solution (continuous delivery)
# See: https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pr: none

variables:
# library variable groups
- group: 'build-tools'
- group: 'keeptrack-prod'
# common task variables
- name: 'BuildConfiguration'
  value: 'Release'
- name: 'SolutionFile'
  value: 'dotnet/KeepTrack.sln'
# specific variables
- name: 'nodejs.version.spec'
  value: '12.x'
- name: 'angular.cli.version'
  value: '8.3.25'
# build environment
- name: 'angular.build.configuration'
  value: 'production'

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: $(nodejs.version.spec)

- task: Npm@1
  displayName: 'Install Angular CLI'
  inputs:
    command: 'custom'
    customCommand: 'install -g @angular/cli@$(angular.cli.version)'

- task: UseDotNet@2
  displayName: 'Use .NET Core SDK'
  inputs:
    packageType: 'sdk'
    version: $(dotnet.sdk.version.lts)

# ASP.NET Core web application

- task: DotNetCoreCLI@2
  displayName: 'Publish the ASP.NET API'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'dotnet/src/**/*Api.csproj'
    arguments: '-c $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)/aspnetapi'
    modifyOutputPath: false
  env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    COREHOST_TRACE: 0

# Angular web application

- task: Npm@1
  displayName: 'Install NPM packages'
  inputs:
    command: 'install'
    workingDir: 'angular-bootstrap'

- task: Bash@3
  displayName: 'Write environment.prod.ts file'
  inputs:
    targetType: 'inline'
    script: |
      cat > angular-bootstrap/src/environments/environment.prod.ts <<EOL
      export const environment = {
        production: true,
        keepTrackApiUrl: '$(keeptrack.api.url)',
        firebase: {
          apiKey: '$(keeptrack.firebase.apikey)',
          authDomain: '$(keeptrack.firebase.projectid).firebaseapp.com',
          databaseURL: 'https://$(keeptrack.firebase.projectid).firebaseio.com',
          projectId: '$(keeptrack.firebase.projectid)',
          storageBucket: '$(keeptrack.firebase.projectid).appspot.com',
          messagingSenderId: '$(keeptrack.firebase.messagingsenderid)',
          appId: '$(keeptrack.firebase.appid)',
          measurementId: '$(keeptrack.firebase.measurementid)'
        }
      };
      EOL

- task: CmdLine@2
  displayName: 'Build Angular application'
  inputs:
    script: |
      ng build --configuration="$(angular.build.configuration)" --outputPath="$(Build.ArtifactStagingDirectory)/angularbootstrap"
    workingDirectory: 'angular-bootstrap'

- task: PublishBuildArtifacts@1
  displayName: 'Save artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
