version: 2
updates:
- package-ecosystem: nuget
  directory: "/dotnet"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: AutoFixture
    versions:
    - 4.15.0
    - 4.16.0
  - dependency-name: Swashbuckle.AspNetCore
    versions:
    - 6.1.0
    - 6.1.1
  - dependency-name: Withywoods.WebTesting
    versions:
    - 1.4.1
  - dependency-name: Withywoods.Configuration
    versions:
    - 1.4.1
  - dependency-name: Microsoft.AspNetCore.Mvc.Testing
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.Extensions.Identity.Core
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Authentication.OpenIdConnect
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Authentication.JwtBearer
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Swashbuckle.AspNetCore.Swagger
    versions:
    - 6.0.2
    - 6.0.4
    - 6.0.5
    - 6.0.7
    - 6.1.0
  - dependency-name: Moq
    versions:
    - 4.16.0
    - 4.16.1
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
  - dependency-name: coverlet.collector
    versions:
    - 3.0.2
    - 3.0.3
  - dependency-name: Microsoft.AspNetCore.Authentication.Google
    versions:
    - 5.0.2
    - 5.0.3
  - dependency-name: Selenium.WebDriver.ChromeDriver
    versions:
    - 88.0.4324.9600
